### ISSUE TITLE
PyPi copy of 0.7.0 not up to date

### ISSUE THREAD

**Issue by sbma44** [scrool/xled#204]
# Summary
Installed from pip and couldn't use set_mode('color'). Installed from source and could.

Running python 3.12.5. PyPi version reported 0.7.0 when using `xled --version`.

```
>>> control.set_mode('color')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/project/.venv/lib/python3.12/site-packages/xled/control.py", line 638, in set_mode
    assert mode in ("movie", "playlist", "rt", "demo", "effect", "off")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

I uninstalled, downloaded the repo, ran `python3 setup.py install`, ignored the deprecation warnings, and the above code worked fine.

(Not sure if this helps but CLI set color did not work even when I had used the app to put the device in color mode. I could see a brief flash when submitting a set-color request, but it'd revert to its previous value. set_mode() and set_led_color_rgb() both work as expected when installing from source)

**Comment by sbma44** [comment]
correction: seems like the 0.7.0 release (as downloaded from the GH releases page) is reflective of what's on PyPi. It's just not what's in HEAD. Closing.
